10  PRINT CHR$(147);     : REM LIMPIAR PANTALLA
20  FOR I=1 TO 5         : REM POTENCIAS DE 2
30  PRINT I,2^I          : REM PINTAR DATOS
40  NEXT I               : REM SIGUIENTE ITERACIÓN
50  PRINT                : REM SALTO DE LINEA
60  FOR I=5 TO 1 STEP -1 : REM LISTA DE NUMEROS
70  PRINT I,6-I          : REM PINTAR DATOS
80  NEXT I               : REM SIGUIENTE ITERACIÓN
90  PRINT                : REM SALTO DE LINEA
100 FOR I=2 TO 10 STEP 2 : REM PARES E IMPARES
110 PRINT I-1,I          : REM PINTAR DATOS
120 NEXT I               : REM SIGUIENTE ITERACIÓN